version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "dependabot-composer"
    allow:
      - dependency-type: "direct"
    labels:
      - "🧱 Dependencies"
    reviewers:
      - "imdhemy"
    versioning-strategy: auto
