version: "3.4"

# Development environment override
services:
  php:
    build:
      target: app_php_dev
    volumes:
      - ./:/srv/app
      - ./docker/php/conf.d/app.dev.ini:/usr/local/etc/php/conf.d/app.dev.ini:ro
      # If you develop on Mac or Windows you can remove the vendor/ directory
      #  from the bind-mount for better performance by enabling the next line:
      #- /srv/app/vendor
    healthcheck:
      interval: 86400s
      timeout: 3s
      retries: 3
      start_period: 30s
    environment:
      # See https://xdebug.org/docs/all_settings#mode
      XDEBUG_MODE: "${XDEBUG_MODE:-develop,debug,coverage}"
    extra_hosts:
      # Ensure that host.docker.internal is correctly defined on Linux
      - host.docker.internal:host-gateway

  caddy:
    volumes:
      - ./public:/srv/app/public:ro
      - ./docker/caddy/Caddyfile:/etc/caddy/Caddyfile:ro

  ###> symfony/mercure-bundle ###
  ###< symfony/mercure-bundle ###

  ###> symfony/mailer ###
  mailer:
    image: schickling/mailcatcher
    container_name: siklid_mailcatcher
    ports:
      - "1025:1025"
      - "1080:1080"
    networks:
      - siklid_network
###< symfony/mailer ###
