name: "Continuous Integration"

on:
  pull_request:
  push:

jobs:
  phpunit:
    name: "PHPUnit tests"

    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Install PHP"
        uses: shivammathur/setup-php@v2
        with:
          coverage: "pcov"
          php-version: "8.2"
          ini-values: memory_limit=-1
          extensions: sodium, fileinfo, redis

      - name: "Start MongoDB"
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: 6.0
          mongodb-db: test

      - name: "Start Redis"
        uses: supercharge/redis-github-action@1.4.0
        with:
          redis-version: 7.0

      - name: "Install dependencies"
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: "locked"

      - name: "Generate openssl keys"
        run: sh ./bin/keypair.sh

      - name: "Tests"
        run: composer test -- --fail-on-warning

  static-analysis-psalm:
    name: "Static Analysis by Psalm"

    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Install PHP"
        uses: shivammathur/setup-php@v2
        with:
          coverage: "none"
          php-version: "8.2"
          ini-values: memory_limit=-1
          extensions: sodium, fileinfo, redis

      - name: "Install dependencies"
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: "locked"

      - name: "psalm"
        run: composer psalm

  coding-standards:
    name: "Check Coding Standards"

    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Install PHP"
        uses: shivammathur/setup-php@v2
        with:
          coverage: "none"
          php-version: "8.2"
          ini-values: memory_limit=-1
          extensions: sodium, fileinfo, redis

      - name: "Install dependencies"
        uses: ramsey/composer-install@v2
        with:
          dependency-versions: "locked"

      - name: "Coding Standard"
        run: composer cs-check
